## store infromation needed for all protocols
locations:
  bedroom:
    x: 0.5
    y: 1.44
    yaw: 0.78     # 45 degrees ≈ 0.78 rad
  living_room:
    x: 1.94
    y: -0.4
    yaw: -0.3
  home:
    x: 0.5
    y: -1.4
    yaw: 3.14     # π rad (180 degrees)
  dining:
    x: 0.5
    y: 1.44
    yaw: 0.78


## need to be integerated to have robot interface get its info 
person_location_state: "person_location"
robot_location_state: "robot_location"

# available type: ## todo set it in a way to verifiy htat yaml doesnt include 
## undefined types: text, audio, video, question_answer 

###
# day:[] or not there means everyday
# optional
# reset_pattern optional         reset_pattern:
          # hours: 1
          # minutes: 30
          # atleast one hours or minutes need to be there

# different types of pattern:
# everytime the protocol is triggered it will be reset
## make sure that /state are turned to false
## reset after 5 mins
# reset_pattern:
#   type: instant 

# reset_pattern:
#   type: periodic
#   hours: 1
#   minutes: 30

## this will be reset depending on the value of blackboard key
# reset_pattern:
#   blackboard_key: last_reset_timestamp 

###
protocols:
  XReminderProtocol:
    medicine_am:
      low_level:
        reminder_1: "/home/olagh48652/smart-home/src/smart-home-robot/shr_resources/resources/food_reminder.mp3"
        type_1: audio
        wait_1: 120
        reminder_2:  "please take your night medicine"
        type_2: text
        number_of_protocols: 2
      high_level:
        priority: 2
        requirements:
          time: {'from': '15:00', 'to': '17:00'}
          permissible_locations: [living_room]

    medicine_pm:
      low_level:
        reminder_1: "please take your night medicine"
        type_1: text
        wait_1: 2*60
        reminder_2: "This is the second reminder to take your night medicine"
        type_2: text
        number_of_protocols: 2
      high_level:
        priority: 2
        success_on: {'state': 'coffee', 'value': True}
        requirements: 
          time: {'from': '10:00', 'to': '15:00'}
          permissible_locations: [living_room]

  ExerciseProtocol:
    exercise:
      low_level:
        exercise_yaml_file: "/home/olagh48652/smart_home_pytree_ws/src/smart_home_robot/smart_home_pytree/config/exercise_routine_test.yaml" 
        video_dir_path: "file:///storage/emulated/0/Download/Exercise_Videos" ## path on the tablet 
        start_state_key: "start_exercise"
        stop_state_key: "stop_exercise"
        get_confirmation: "Do you want to exercise now?" ## if empty then dont ask to indictae whther the protocol should start after the person asks
      high_level:
        reset_pattern:
          type: instant ## if triggered should play directly
        priority: 4
        requirements: 
          event: 
            - {'state': 'start_exercise', 'value': True}
          time: {'from': '15:00', 'to': '17:00'}

  ChargeRobot:
    charge_robot: 
      high_level:
        priority: 100
        reset_pattern:
          type: instant 
        requirements:
          event: 
              - {'state': 'charging', 'value': False}

  MoveAwayProtocol:
    move_away:
      low_level:
        away_location: dining # move_away has two loc, home or away where away is the location defined here and has to be part of the locations in the yaml
        position_state_key: position # key to indicate whether to move away or home
        state_key: move_away
      high_level:
        reset_pattern:
          type: instant 
        priority: 1
        requirements: 
          event: 
            - {'state': 'move_away', 'value': True}  
